name: Descomprimir ZIP
on:
  push:
    branches: [ main ]
jobs:
  unzip:
    runs-on: ubuntu-latest
    steps:
      - name: Clonar repositorio
        uses: actions/checkout@v3

      - name: Descomprimir archivo
        run: |
          unzip -o *.zip -d .
          rm *.zip

      - name: Guardar carpetas en GitHub
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git add .
          git commit -m "Carpetas descomprimidas automaticamente" || exit 0
          git push
